"""
Diagnostic Report Generator (6th agent, optional).

Problem this module solves: each agent (DriftDetector, TargetDriftAgent,
PerformanceDriftAgent) already computes a very detailed diagnosis (PSI +
Wasserstein per feature, std_score per metric, SHAP/VIF rationale...), and
AlertAgent already turns that into expert-level `recommended_action` text,
case by case. But all of that:

1. Gets PUSHED (log/Slack/email) then lost -- AlertDispatcher isn't meant
   to be re-read as a report, only to notify in the moment.
2. Gets TRUNCATED before the alert: `AlertAgent.process_data_drift` only
   mentions the first 5 features per priority group (`group[:5]`) in the
   message -- correct to avoid flooding Slack, but means an engineer who
   wants to see all 12 drifted features has nowhere to look.
3. Only exists as individual Alert/RemediationAction objects -- there's
   never a SINGLE coherent artifact answering "what happened this cycle,
   across every drift type, with full detail and recommended remediation"
   -- the equivalent of an incident report an engineer can open.

This module doesn't recompute anything or reinvent any decision logic: it
reads the results already produced by the 3 detectors + the Alert/
RemediationAction objects already generated by AlertAgent/RemediationAgent,
and ASSEMBLES them into a single DiagnosticReport, complete (no 5-item
truncation), rendered as Markdown (readable, directly usable by an
engineer) + JSON (archivable, queryable), and PERSISTED to disk -- unlike
alerts, which are only a transient stream.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
import io
import json
import logging
import re
from pathlib import Path
from typing import Any, Dict, List, Optional

# Aliased (not "markdown") because DiagnosticReportGenerator.save() already
# uses a local variable named `markdown` for the report's Markdown text --
# keeping the import name distinct avoids any risk of shadowing confusion.
import markdown as _markdown_to_html
from xhtml2pdf import pisa

from alert_agent import Alert, AlertPriority
from drift_detector import DriftReport
from feature_intelligence import FeatureIntelligenceContext, FeatureRiskAssessor
from performance_drift_agent import PerformanceDriftResult
from remediation_agent import RemediationAction
from target_drift_agent import LabelStatus, TargetDriftResult

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------- #
# Overall status: reuses the MAX priority already computed by AlertAgent
# instead of re-deriving overall severity independently -- two synthesis
# paths that could diverge on the same data would be the same class of bug
# psi_common.py already fixed once for PSI (see drift_detector.py).
# ---------------------------------------------------------------------- #

_STATUS_BY_PRIORITY = {
    AlertPriority.PAGE: "page",
    AlertPriority.CRITICAL: "critical",
    AlertPriority.WARNING: "degraded",
    AlertPriority.INFO: "info",
}
_STATUS_RANK = {"healthy": 0, "info": 1, "degraded": 2, "critical": 3, "page": 4}


def _overall_status(alerts: List[Alert]) -> str:
    status = "healthy"
    for a in alerts:
        candidate = _STATUS_BY_PRIORITY.get(a.priority, "info")
        if _STATUS_RANK[candidate] > _STATUS_RANK[status]:
            status = candidate
    return status


# ---------------------------------------------------------------------- #
# Report
# ---------------------------------------------------------------------- #

@dataclass
class DiagnosticReport:
    model_id: str
    cycle_timestamp: str          # timestamp of the most recent signal used (traceability)
    generated_at: str
    overall_status: str           # "healthy" | "info" | "degraded" | "critical" | "page"
    executive_summary: str
    data_drift: Optional[Dict[str, Any]]
    target_drift: Optional[Dict[str, Any]]
    performance_drift: Optional[Dict[str, Any]]
    root_cause: Optional[Dict[str, Any]]
    alerts: List[Dict[str, Any]]
    remediation_actions: List[Dict[str, Any]]

    def to_dict(self) -> Dict[str, Any]:
        return {
            "model_id": self.model_id,
            "cycle_timestamp": self.cycle_timestamp,
            "generated_at": self.generated_at,
            "overall_status": self.overall_status,
            "executive_summary": self.executive_summary,
            "data_drift": self.data_drift,
            "target_drift": self.target_drift,
            "performance_drift": self.performance_drift,
            "root_cause": self.root_cause,
            "alerts": self.alerts,
            "remediation_actions": self.remediation_actions,
        }

    # ------------------------------------------------------------------ #
    # Markdown rendering -- THE format meant for an engineer to read: full
    # detail (no 5-item truncation like in alert messages), one page to
    # open to understand a whole monitoring cycle.
    # ------------------------------------------------------------------ #

    def to_markdown(self) -> str:
        lines: List[str] = []
        badge = {"healthy": "🟢", "info": "🔵", "degraded": "🟡", "critical": "🔴", "page": "🚨"}
        lines.append(f"# Diagnostic report -- `{self.model_id}`")
        lines.append("")
        lines.append(f"**Overall status: {badge.get(self.overall_status, '')} {self.overall_status.upper()}**")
        lines.append(f"Generated at {self.generated_at} | Cycle (most recent signal): {self.cycle_timestamp}")
        lines.append("")
        lines.append("## Executive summary")
        lines.append("")
        lines.append(self.executive_summary)
        lines.append("")

        if self.root_cause:
            lines.append("## 🔴 Probable root cause identified (cross-agent corroboration)")
            lines.append("")
            lines.append(f"**{self.root_cause['title']}**")
            lines.append("")
            lines.append(self.root_cause["message"])
            lines.append("")
            lines.append(f"**Recommended action:** {self.root_cause['recommended_action']}")
            lines.append("")

        if self.data_drift:
            lines.extend(self._render_data_drift())
        if self.target_drift:
            lines.extend(self._render_target_drift())
        if self.performance_drift:
            lines.extend(self._render_performance_drift())

        lines.extend(self._render_alerts())
        lines.extend(self._render_remediation())

        return "\n".join(lines)

    # -- Detailed sections, one per drift type -----------------------

    def _render_data_drift(self) -> List[str]:
        d = self.data_drift
        out = [
            "## 1. Data / Feature Drift",
            "",
            f"Overall severity: **{d['overall_severity']}** -- "
            f"{d['drifted_features']}/{d['total_features']} feature(s) drifted "
            f"({d['drift_percentage']:.1f}%).",
            "",
        ]
        rows = d["features"]
        if rows:
            has_risk = any(r.get("risk_level") for r in rows)
            has_quality_issue = any(
                (r.get("missing_rate") or 0) >= 0.05 or r.get("new_categories") for r in rows
            )
            header = ["Feature", "Type", "PSI", "Wasserstein (norm)", "Severity", "Drifted"]
            if has_quality_issue:
                header += ["Quality"]
            if has_risk:
                header += ["Risk Level (SHAP/VIF)", "Rationale"]
            out.append("| " + " | ".join(header) + " |")
            out.append("|" + "---|" * len(header))
            for r in rows:
                row = [
                    r["feature"], r["type"], f"{r['psi_score']:.4f}",
                    f"{r['norm_wasserstein_distance']:.4f}" if r["norm_wasserstein_distance"] is not None else "n/a",
                    r["severity"], "yes" if r["is_drifted"] else "no",
                ]
                if has_quality_issue:
                    missing_rate = r.get("missing_rate")
                    new_cats = r.get("new_categories") or []
                    flags = []
                    if missing_rate is not None and missing_rate >= 0.05:
                        flags.append(f"⚠️ {missing_rate*100:.1f}% missing")
                    if new_cats:
                        flags.append(f"⚠️ new: {', '.join(new_cats[:3])}")
                    row += [" / ".join(flags) if flags else "ok"]
                if has_risk:
                    row += [r.get("risk_level") or "n/a", (r.get("rationale") or "").replace("|", "/")]
                out.append("| " + " | ".join(row) + " |")
            out.append("")
        return out

    def _render_target_drift(self) -> List[str]:
        t = self.target_drift
        out = ["## 2. Target Drift", "", f"Status: **{t['status']}** | n_samples = {t['n_samples']}", ""]
        if t["drift"] is None:
            out.append("No computation this cycle (PENDING -- no usable labels/predictions yet).")
        else:
            drift = t["drift"]
            out.append(f"PSI = {drift['psi_score']:.4f} | severity = **{drift['severity']}** | drifted = {'yes' if drift['is_drifted'] else 'no'}")
            if drift.get("norm_wasserstein_distance") is not None:
                out.append(f"Wasserstein distance (normalized) = {drift['norm_wasserstein_distance']:.4f}")
            details = drift.get("details") or {}
            if "chi2_statistic" in details and details["chi2_statistic"] is not None:
                out.append(f"Chi2 = {details['chi2_statistic']:.3f} (p-value = {details['chi2_pvalue']:.4f})")
            elif details.get("chi2_note"):
                out.append(f"Chi2 skipped: {details['chi2_note']}")
            if "reference_mean" in details:
                out.append(
                    f"Reference mean = {details['reference_mean']:.4f} -> "
                    f"current mean = {details['current_mean']:.4f} "
                    f"(reference std = {details['reference_std']:.4f} -> current std = {details['current_std']:.4f})"
                )
            if details.get("note"):
                out.append(f"_Note: {details['note']}_")
        out.append("")
        return out

    def _render_performance_drift(self) -> List[str]:
        p = self.performance_drift
        out = [
            "## 3. Performance Drift", "",
            f"Status: **{p['status']}** | severity: **{p['severity']}** | "
            f"remediation_type: `{p['remediation_type']}` | window = {p['window_size']} samples",
        ]
        if p.get("proba_coverage") is not None:
            out.append(f"y_proba coverage over the window: {p['proba_coverage']*100:.1f}%")
        out.append("")

        def _metric_table(title: str, metrics: List[Dict[str, Any]]) -> List[str]:
            if not metrics:
                return []
            lines = [f"### {title}", "", "| Metric | Baseline | Current | Delta | Std score | Degraded | Contributes to severity |", "|---|---|---|---|---|---|---|"]
            for m in metrics:
                lines.append(
                    f"| {m['name']} | {m['baseline']:.4f} | {m['current']:.4f} | {m['delta']:+.4f} | "
                    f"{m['std_score']:+.2f} | {'yes' if m['degraded'] else 'no'} | {'yes' if m.get('contributes_to_severity', True) else 'no'} |"
                )
            lines.append("")
            return lines

        out.extend(_metric_table("Performance metrics", p["metrics"]))
        out.extend(_metric_table("Calibration metrics", p["calibration_metrics"]))

        if p.get("notes"):
            out.append("**Notes:**")
            for n in p["notes"]:
                out.append(f"- {n}")
            out.append("")
        return out

    def _render_alerts(self) -> List[str]:
        if not self.alerts:
            return ["## Alerts raised this cycle", "", "None.", ""]
        out = [f"## Alerts raised this cycle ({len(self.alerts)})", ""]
        order = {"page": 0, "critical": 1, "warning": 2, "info": 3}
        for a in sorted(self.alerts, key=lambda x: order.get(x["priority"], 9)):
            icon = {"page": "🚨", "critical": "🔴", "warning": "🟡", "info": "🔵"}.get(a["priority"], "")
            out.append(f"### {icon} [{a['priority'].upper()}] {a['title']} _(source: {a['source_agent']})_")
            out.append("")
            out.append(a["message"].replace("\n", "  \n"))
            out.append("")
            if a.get("recommended_action"):
                out.append(f"**Recommended action (expert):** {a['recommended_action']}")
                out.append("")
            out.append(f"_Remediation type: `{a['remediation_type']}`_")
            out.append("")
        return out

    def _render_remediation(self) -> List[str]:
        if not self.remediation_actions:
            return ["## Remediation actions", "", "None generated this cycle.", ""]
        out = [f"## Remediation actions ({len(self.remediation_actions)})", "",
               "| Type | Urgency (SLA) | Status | Approval required | Automatable | Source alert |",
               "|---|---|---|---|---|---|"]
        for r in self.remediation_actions:
            urgency = r.get("urgency", "normal")
            sla = r.get("sla", "")
            label = f"{urgency} ({sla})" if sla else urgency
            if r.get("is_primary") is False and r.get("superseded_by"):
                label += f" -- superseded by '{r['superseded_by']}'"
            out.append(
                f"| {r['action_type']} | {label} | {r['status']} | {'yes' if r['requires_approval'] else 'no'} | "
                f"{'yes' if r['automatable'] else 'no'} | {r['source_alert_title']} |"
            )
        out.append("")
        return out


# ---------------------------------------------------------------------- #
# Generator
# ---------------------------------------------------------------------- #

class DiagnosticReportGenerator:
    """Assembles a DiagnosticReport from the outputs ALREADY computed by the
    3 detectors + the Alert/RemediationAction objects already produced, and
    persists it to disk. Recomputes and redecides nothing -- pure
    presentation/archival layer on top of the existing agents."""

    def __init__(self, output_dir: str = "reports"):
        self.output_dir = Path(output_dir)

    # -- Construction ------------------------------------------------------

    def generate(
        self,
        model_id: str,
        data_drift_report: Optional[DriftReport] = None,
        target_drift_result: Optional[TargetDriftResult] = None,
        performance_drift_result: Optional[PerformanceDriftResult] = None,
        alerts: Optional[List[Alert]] = None,
        remediation_actions: Optional[List[RemediationAction]] = None,
        feature_intelligence: Optional[FeatureIntelligenceContext] = None,
    ) -> DiagnosticReport:
        alerts = alerts or []
        remediation_actions = remediation_actions or []

        assessor = FeatureRiskAssessor(feature_intelligence) if feature_intelligence is not None else None

        data_drift_dict = self._render_data_drift_section(data_drift_report, assessor) if data_drift_report else None
        target_drift_dict = self._render_target_drift_section(target_drift_result) if target_drift_result else None
        performance_dict = performance_drift_result.to_dict() if performance_drift_result else None

        root_cause_alert = next((a for a in alerts if a.source_agent == "root_cause"), None)
        root_cause_dict = (
            {"title": root_cause_alert.title, "message": root_cause_alert.message,
             "recommended_action": root_cause_alert.recommended_action}
            if root_cause_alert else None
        )

        cycle_timestamp = max(
            [t.timestamp for t in (data_drift_report, target_drift_result, performance_drift_result) if t is not None],
            default=datetime.now(timezone.utc).isoformat(),
        )

        report = DiagnosticReport(
            model_id=model_id,
            cycle_timestamp=cycle_timestamp,
            generated_at=datetime.now(timezone.utc).isoformat(),
            overall_status=_overall_status(alerts),
            executive_summary=self._executive_summary(
                alerts, remediation_actions, data_drift_report, target_drift_result, performance_drift_result
            ),
            data_drift=data_drift_dict,
            target_drift=target_drift_dict,
            performance_drift=performance_dict,
            root_cause=root_cause_dict,
            alerts=[a.to_dict() for a in alerts],
            remediation_actions=[r.to_dict() for r in remediation_actions],
        )
        return report

    @staticmethod
    def _render_data_drift_section(report: DriftReport, assessor: Optional[FeatureRiskAssessor]) -> Dict[str, Any]:
        features = []
        for r in report.feature_results:  # ALL features, not just the first 5 (see module docstring)
            entry = {
                "feature": r.feature_name,
                "type": r.feature_type.value,
                "psi_score": r.psi_score,
                "norm_wasserstein_distance": r.norm_wasserstein_dist,
                "severity": r.severity.value,
                "is_drifted": r.is_drifted,
                "risk_level": None,
                "rationale": None,
                "missing_rate": r.details.get("missing_rate"),
                "new_categories": r.details.get("new_categories") or [],
            }
            if assessor is not None:
                try:
                    assessment = assessor.assess(r.feature_name)
                    entry["risk_level"] = assessment.risk_level.value
                    entry["rationale"] = assessment.rationale
                except Exception as exc:  # noqa: BLE001 -- feature missing from SHAP/VIF context, degrade gracefully
                    logger.debug(f"No risk assessment for '{r.feature_name}': {exc}")
            features.append(entry)

        return {
            "overall_severity": report.overall_severity.value,
            "total_features": report.total_features,
            "drifted_features": report.drifted_features,
            "drift_percentage": report.drift_percentage,
            "features": features,
            "timestamp": report.timestamp,
        }

    @staticmethod
    def _render_target_drift_section(result: TargetDriftResult) -> Dict[str, Any]:
        return result.to_dict()

    @staticmethod
    def _executive_summary(
        alerts: List[Alert],
        remediation_actions: List[RemediationAction],
        data_drift_report: Optional[DriftReport],
        target_drift_result: Optional[TargetDriftResult],
        performance_drift_result: Optional[PerformanceDriftResult],
    ) -> str:
        parts: List[str] = []

        if data_drift_report is not None:
            parts.append(
                f"Data drift: {data_drift_report.drifted_features}/{data_drift_report.total_features} "
                f"feature(s) drifted (severity {data_drift_report.overall_severity.value})."
            )
        if target_drift_result is not None and target_drift_result.status != LabelStatus.PENDING and target_drift_result.drift:
            parts.append(
                f"Target drift ({target_drift_result.status.value}): "
                f"PSI={target_drift_result.drift.psi_score:.3f}, severity {target_drift_result.drift.severity.value}."
            )
        if performance_drift_result is not None and performance_drift_result.severity is not None:
            parts.append(
                f"Performance: severity {performance_drift_result.severity.value}"
                + (f", cause = {performance_drift_result.remediation_type}." if performance_drift_result.remediation_type else ".")
            )

        counts: Dict[str, int] = {}
        for a in alerts:
            counts[a.priority.value] = counts.get(a.priority.value, 0) + 1
        if counts:
            parts.append("Alerts: " + ", ".join(f"{v} {k}" for k, v in sorted(counts.items(), key=lambda kv: kv[0])) + ".")
        else:
            parts.append("No alerts raised this cycle.")

        pending = sum(1 for r in remediation_actions if r.requires_approval and r.status != "approved")
        if pending:
            parts.append(f"{pending} remediation action(s) pending human approval.")

        if not parts:
            parts.append("No usable signal this cycle (no detector produced a result).")

        return " ".join(parts)

    # -- PDF rendering ---------------------------------------------------

    # One CSS per overall_status, reusing the same severity palette as the
    # HTML emails (run_scenario.py::_build_executive_email,
    # bridge/senders.py::_render_alert_html) so a PAGE/CRITICAL report is
    # visually unmistakable, not just another gray PDF.
    _STATUS_ACCENT = {
        "page": "#7C0A0A", "critical": "#C0392B", "degraded": "#D68910",
        "info": "#2E86C1", "healthy": "#1E8449",
    }

    # xhtml2pdf has no color-emoji font support -- unlike a terminal or a
    # Markdown viewer, it renders these as solid black tofu boxes, which
    # looks like a rendering bug rather than a badge. The words right next
    # to each emoji already carry the same information ("CRITICAL",
    # "PAGE", the "missing"/"new:" flags), so stripping them loses nothing
    # in the PDF specifically -- the .md/.json files keep the emojis as-is.
    _PDF_STRIP_CHARS = "🟢🔵🟡🔴🚨⚠️"

    def _render_pdf(self, report: "DiagnosticReport", markdown_text: str) -> bytes:
        """Converts the report's Markdown to a styled PDF (Markdown -> HTML
        via `markdown`, HTML -> PDF via `xhtml2pdf`, both pure-Python, no
        system library like wkhtmltopdf/Cairo required). Raises on failure
        -- the caller (save()) decides how to degrade, this method just
        renders."""
        accent = self._STATUS_ACCENT.get(report.overall_status, "#5D6D7E")
        pdf_source = markdown_text
        for ch in self._PDF_STRIP_CHARS:
            pdf_source = pdf_source.replace(ch, "")
        # Collapse the double space left behind on each line (e.g. "## 🔴 Title"
        # -> "##  Title") WITHOUT touching newlines, which Markdown needs
        # (a blank line = paragraph break, a lone "\n" inside a table row
        # matters for pipe alignment).
        pdf_source = "\n".join(re.sub(r"[ \t]{2,}", " ", line) for line in pdf_source.split("\n"))
        body_html = _markdown_to_html.markdown(pdf_source, extensions=["tables", "fenced_code"])

        css = f"""
        <style>
            @page {{ size: A4; margin: 2cm 1.8cm; }}
            body {{ font-family: Helvetica, Arial, sans-serif; font-size: 10.5pt; color: #1C2833; }}
            h1 {{ color: #FFFFFF; background-color: {accent}; padding: 10px 14px;
                  font-size: 16pt; border-radius: 4px; }}
            h2 {{ color: {accent}; border-bottom: 1px solid #EAECEE; padding-bottom: 4px;
                  margin-top: 22px; font-size: 13pt; }}
            h3 {{ color: #1C2833; font-size: 11.5pt; }}
            table {{ border-collapse: collapse; width: 100%; margin: 10px 0 16px; }}
            th {{ background-color: #F4F6F7; border: 1px solid #D5D8DC; padding: 5px 8px;
                  font-size: 9pt; text-align: left; }}
            td {{ border: 1px solid #EAECEE; padding: 5px 8px; font-size: 9pt; }}
            code, pre {{ font-family: Courier, monospace; font-size: 9pt;
                         background-color: #F8F9F9; }}
            strong {{ color: #1C2833; }}
            hr {{ border: none; border-top: 1px solid #EAECEE; }}
            .footer {{ margin-top: 24px; font-size: 8pt; color: #909497; }}
        </style>
        """
        html_full = (
            f"<html><head><meta charset='utf-8'/>{css}</head>"
            f"<body>{body_html}"
            f"<p class='footer'>Generated automatically by the drift monitoring pipeline.</p>"
            f"</body></html>"
        )

        buffer = io.BytesIO()
        result = pisa.CreatePDF(html_full, dest=buffer, encoding="utf-8")
        if result.err:
            raise RuntimeError(f"xhtml2pdf reported {result.err} error(s) rendering the report to PDF")
        return buffer.getvalue()

    # -- Persistence ---------------------------------------------------

    def save(self, report: DiagnosticReport) -> Dict[str, str]:
        """Writes the report as Markdown + JSON + PDF, timestamped, under
        `reports/<model_id>/<timestamp>.{md,json,pdf}`, updates a
        `latest.{md,json,pdf}` pointer for direct access without listing
        the directory, and logs a summary line to `index.jsonl`
        (append-only, same principle as AlertDispatcher's dead-letter
        queue) so the history can be browsed without reopening every
        report.

        PDF rendering is best-effort: on failure (missing dependency,
        malformed Markdown edge case...) the Markdown/JSON files are still
        written and `pdf_path` is simply absent from the returned dict --
        callers (see run_scenario.py) fall back to attaching the Markdown
        file rather than crashing the whole reporting step over a
        cosmetic failure."""
        model_dir = self.output_dir / report.model_id
        model_dir.mkdir(parents=True, exist_ok=True)

        safe_ts = report.generated_at.replace(":", "-")
        md_path = model_dir / f"{safe_ts}.md"
        json_path = model_dir / f"{safe_ts}.json"
        pdf_path = model_dir / f"{safe_ts}.pdf"
        latest_md_path = model_dir / "latest.md"
        latest_json_path = model_dir / "latest.json"
        latest_pdf_path = model_dir / "latest.pdf"
        index_path = model_dir / "index.jsonl"

        markdown = report.to_markdown()
        payload = report.to_dict()

        md_path.write_text(markdown, encoding="utf-8")
        json_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
        latest_md_path.write_text(markdown, encoding="utf-8")
        latest_json_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")

        paths = {
            "markdown_path": str(md_path),
            "json_path": str(json_path),
            "latest_markdown_path": str(latest_md_path),
        }

        try:
            pdf_bytes = self._render_pdf(report, markdown)
            pdf_path.write_bytes(pdf_bytes)
            latest_pdf_path.write_bytes(pdf_bytes)
            paths["pdf_path"] = str(pdf_path)
            paths["latest_pdf_path"] = str(latest_pdf_path)
        except Exception as exc:
            logger.warning(
                f"[{report.model_id}] PDF rendering failed, keeping Markdown/JSON only "
                f"(report itself is not affected): {exc}"
            )

        try:
            with open(index_path, "a", encoding="utf-8") as f:
                f.write(json.dumps({
                    "generated_at": report.generated_at,
                    "cycle_timestamp": report.cycle_timestamp,
                    "overall_status": report.overall_status,
                    "n_alerts": len(report.alerts),
                    "n_remediation_actions": len(report.remediation_actions),
                    "path": str(md_path),
                    "pdf_path": paths.get("pdf_path"),
                }, ensure_ascii=False) + "\n")
        except Exception as exc:
            logger.error(f"Failed to write the report index for '{report.model_id}': {exc}")

        return paths


# ---------------------------------------------------------------------- #
# LangGraph integration -- optional node, wire AFTER "remediation" and
# BEFORE the existing routing to "human_review"/END (see orchestrator.py::
# build_graph):
#
#   from diagnostic_report import DiagnosticReportGenerator, report_node
#   _report_generator = DiagnosticReportGenerator()
#   graph.add_node("diagnostic_report", report_node)
#   graph.add_edge("remediation", "diagnostic_report")
#   graph.add_conditional_edges(
#       "diagnostic_report", _route_after_remediation, {"human_review": "human_review", END: END}
#   )
#
# Add to MonitoringState (TypedDict): `report_path: str`,
# `report_pdf_path: Optional[str]`, and `report_status: str` --
# deliberately NOT the report content itself (potentially long Markdown/
# PDF bytes) in the checkpointed State, only on-disk paths, same logic as
# features_df/_BATCH_DATA.
# ---------------------------------------------------------------------- #

def report_node(state: Dict[str, Any], generator: Optional[DiagnosticReportGenerator] = None) -> Dict[str, Any]:
    """Assembles and persists the current cycle's DiagnosticReport.

    Reads `state["_alert_objects"]` (set by alerting_node) and
    `state["_remediation_action_objects"]` (set by remediation_node) -- the
    RAW objects for the current cycle, not their serialized/capped history."""
    generator = generator or DiagnosticReportGenerator()

    report = generator.generate(
        model_id=state["model_id"],
        data_drift_report=state.get("data_drift_report"),
        target_drift_result=state.get("target_drift_result"),
        performance_drift_result=state.get("performance_drift_result"),
        alerts=state.get("_alert_objects", []),
        remediation_actions=state.get("_remediation_action_objects", []),
    )
    paths = generator.save(report)

    logger.info(
        f"[{state['model_id']}] Diagnostic report ({report.overall_status}) -> "
        f"{paths.get('pdf_path') or paths['markdown_path']}"
    )

    return {
        **state,
        "report_path": paths["markdown_path"],
        # Absent (None) if PDF rendering failed this cycle -- see
        # DiagnosticReportGenerator.save()'s docstring on why that's
        # best-effort rather than fatal.
        "report_pdf_path": paths.get("pdf_path"),
        "report_status": report.overall_status,
        # Short (1-3 sentence) plain-language summary, cheap enough to keep
        # in checkpointed state as-is (unlike the full Markdown, kept only
        # on disk). Lets a caller (e.g. run_scenario.py) send a short
        # professional email with the full technical report attached,
        # instead of dumping PSI tables/rationale into the email body.
        "report_executive_summary": report.executive_summary,
    }
